version: 2
orbs: 
  cypress: cypress-io/cypress@1.5.1
workflows:
  version: 2
  regular-workflow:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          start: npm run ci:start
          wait-on: 'http://localhost:8000'
          store_artifacts: true