version: 2.1
orbs: 
  cypress: cypress-io/cypress@1.5.1
jobs:
  lint:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm ci
      - save_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache/Cypress
      - run:
          name: eslint
          command: npm run lint
workflows:
  version: 2.1
  regular-workflow:
    jobs:
      - lint
      - cypress/install:
          requires:
            - lint
      - cypress/run:
          requires:
            - cypress/install
          start: npm run ci:start
          wait-on: 'http://localhost:8000'
          store_artifacts: true